version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app